import { NavBar } from "@/components/NavBar";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import { ReactNode } from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Canvaly",
  description: "Generated by create next app",
};

interface AuthLayoutProps {
  children: ReactNode;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <NavBar />
          <div className="flex justify-center itens-center w-full max-w-7xl mx-auto">
            <AuthLayout>{children}</AuthLayout>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}

function AuthLayout({ children }: AuthLayoutProps) {
  return (
    <div>
      {children}
      <Toaster />
    </div>
  );
}
